"""add_customer_addresses_order_shipping_snapshot_session_checkout_state

Revision ID: c120975a8456
Revises: 23622d38bfbf
Create Date: 2026-08-27 21:39:12.820099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c120975a8456'
down_revision: Union[str, Sequence[str], None] = '23622d38bfbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=500), nullable=False),
    sa.Column('address_line_2', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_addresses_customer_id'), 'customer_addresses', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_addresses_id'), 'customer_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_customer_addresses_is_default'), 'customer_addresses', ['is_default'], unique=False)
    op.create_index(op.f('ix_customer_addresses_label'), 'customer_addresses', ['label'], unique=False)
    op.add_column('agent_sessions', sa.Column('checkout_state', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('customer_address_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('shipping_recipient_name', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_address_line_1', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('shipping_address_line_2', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_state', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('shipping_country', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_orders_customer_address_id'), 'orders', ['customer_address_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'customer_addresses', ['customer_address_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_customer_address_id'), table_name='orders')
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_address_line_2')
    op.drop_column('orders', 'shipping_address_line_1')
    op.drop_column('orders', 'shipping_recipient_name')
    op.drop_column('orders', 'customer_address_id')
    op.drop_column('agent_sessions', 'checkout_state')
    op.drop_index(op.f('ix_customer_addresses_label'), table_name='customer_addresses')
    op.drop_index(op.f('ix_customer_addresses_is_default'), table_name='customer_addresses')
    op.drop_index(op.f('ix_customer_addresses_id'), table_name='customer_addresses')
    op.drop_index(op.f('ix_customer_addresses_customer_id'), table_name='customer_addresses')
    op.drop_table('customer_addresses')
    # ### end Alembic commands ###
